### ISSUE TITLE
No file named align.sh

### ISSUE THREAD

**Issue by saireddy12** [sweekarsud/Goodness-of-Pronunciation#4]
can you please clearly explain how to generate the input files
and what are required files for input data creation
 
can you guide me to train nnet3 model (I am not able to  understand the documentation)

following your previous comments in the issues  section i executed following commands
nnet3bin/nnet3-compute--apply-exp=true (executed)

"/nnet3/align.sh" to get the align result.(no file found error ) I recently configured kaldi on colab

Steps I performed:-
1.Properly Installed kaldi in colab notebook
2.cloned your repository and extracted in the said path(kaldi/egs/Native_Acoustic_Model/s5/Goodness-of-Pronunciation)
Now i am unable to get the input files 

Extra Information: my use-case is that i need a GoP score(0-100) for an audio . The audio   is an english answer to questions like Introduce yourself
I am new to this so please help me.

**Comment by sweekarsud** [comment]
Please refer our Interspeech paper on how to generate the input files required in order to generate the GOP score. Also if you have issues while generating the input files on Kaldi then kindly refer its documentation and the GitHub repository which clearly mentions how to train the model from scratch. To find the location of align.sh also please refer the GitHub repository.

Please NOTE: The input files have been created by us, by training the model from scratch using LibriSpeech and other datasets, so you will need to use these datasets and prepare your model. These files are not pre-created and available to use.
